@ProductAPI_HostAddress = http://localhost:5093

POST {{ProductAPI_HostAddress}}/api/Product/AddProduct
Content-Type: application/json
{
  "Name": "Mobile",
  "Price": 500
}
###
GET {{ProductAPI_HostAddress}}/api/Product/GetAllProduct
